name: Deploy para KingHost via FTP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      # Deploy via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftp

          # Pasta local com apenas os arquivos públicos do site
          local-dir: dist/
          
          # Pasta do site no KingHost (certifique que já existe)
          server-dir: public_html/

          # Arquivo para controlar o estado do deploy
          state-name: .ftp-deploy-sync-state.json

          # Nível de logs
          log-level: verbose

          # Evita subir arquivos desnecessários
          exclude: |
            .git
            .git/**
            .github
            .github/**
            node_modules/**
            .vscode/**
            README.md
            *.yml