name: Deploy para KingHost via FTP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftp

          local-dir: ./
          server-dir: /public_html/

          state-name: .ftp-deploy-sync-state.json
          log-level: verbose

          exclude: |
            .git
            .git/**
            .github
            .github/**
            node_modules/**
            .vscode/**